spring:
  application:
    name: vuelco

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB

server:
  tomcat:
    max-http-form-post-size: 50MB
    max-swallow-size: 50MB