spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:localhost;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    username: sa
    password: 
    driver-class-name: org.h2.Driver